# Generated by Django 4.2.1 on 2023-07-03 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField(max_length=3)),
                ('humidity', models.IntegerField(max_length=3)),
                ('date_of_creation', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
